//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.MedicalProcedures = new HashSet<MedicalProcedures>();
        }
    
        public int ID_Staff { get; set; }
        public string FullName { get; set; }
        public int ID_Department { get; set; }
        public int ID_Position { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int ID_Role { get; set; }
        public string Password { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalProcedures> MedicalProcedures { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
